@baseUrl = http://localhost:3333

### Goals
POST {{baseUrl}}/goals
Content-Type: application/json

{
  "title":"Swim",
  "desiredWeeklyFrequency": 3
}

### @queue
GET {{baseUrl}}/goals

### @/nodes/:url
GET {{baseUrl}}/nodes/:url