@baseUrl = http://localhost:3333

### Goals POST
POST {{baseUrl}}/goals
Content-Type: application/json

{
  "title":"Swim",
  "desiredWeeklyFrequency": 3
}

### Completions POST
POST {{baseUrl}}/completions
Content-Type: application/json

{
  "goalId":"ap5dw0tbdv0xbvt4t92ocowd"
}

### @goals
GET {{baseUrl}}/goals

### @pending-goals
GET {{baseUrl}}/pending-goals